# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: mattc007.github.io
description: Matt Catrett
title: Matt Catrett
author:
  name: Matt Catrett
  email: mcatrett@gmail.com

# google analytics
ga:
  code: UA-35639171-1

twitter: mattcatrett
github: Mattc007

paginator_path: _posts
paginate: 1

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true
